apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  namespace: food-delivery
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: order-service:1.0
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              value: "postgresql"
            - name: DB_USER
              value: "postgres"
            - name: DB_PASSWORD
              value: "postgres123"
            - name: DB_NAME
              value: "fooddelivery"
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: food-delivery
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: order-service
